name: "Build and Deploy"

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      # 构建站点，强制指定 baseurl 为空，输出到 _site
      - name: Build site
        run: bundle exec jekyll build -d "_site" --baseurl ""
        env:
          JEKYLL_ENV: "production"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

      # 暂时禁用 htmlproofer 检查，避免因缺失资源导致构建失败
      # 等你上传完头像、favicon 等资源后，可以取消下面几行的注释
      - name: Test site
        run: |
         bundle exec htmlproofer _site \
           \-\-disable-external \
           \-\-ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
